import type { Metadata } from "next";
import { geistSans , geistMono , roboto ,arimo ,nic } from "@/lib/fonts";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import SmoothScroll from "@/components/smoothScroll";

export const metadata: Metadata = {
  title: "Arin Chandrakar | Developer & Learner ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${arimo.variable} ${nic.variable} ${roboto.variable} h-full antialiased`}
    >
      
      <body className={`${geistSans.variable} ${geistMono.variable} ${arimo.variable} ${nic.variable} ${roboto.variable}`}>
        <SmoothScroll>
        <div className="dark:bg-black border-r border-l border-white/20 border-dotted container min-h-full flex flex-col relative max-w-4xl mx-auto">
          <Navbar/>
          {children}
        </div>
        </SmoothScroll>
      </body>
    </html>
  );
}
